name: bluesky_2022_10

# use:
#   date; conda env create --force -f ./environment_2022_2.yml; date

channels:
  - defaults
  - conda-forge
  - aps-anl-tag
  - nsls2forge

dependencies:
  # --- Python core packages
  - python=3.10
  - ipython
  - jupyter
  - jupyterlab
  - notebook
  - pip
  - psutil
  # --- testing and quality assurance
  - black
  - flake8
  - pylint
  - pytest
  # --- Qt
  - pyqt=5
  - qt=5
  # --- support packages
  - aps-dm-api>=5
  - epics-base>=7.0.5
  - h5py
  - imagecodecs-lite
  - ipympl
  - lxml
  - pandas
  - pint
  - pyEpics>=3.5.0
  - pymongo
  - scikit-image
  - xlrd
  # --- Bluesky framework packages
  - apstools>=1.6.8
  - area-detector-handlers
  - bluesky>=1.8.1
  - bluesky-queueserver
  - bluesky-widgets
  - databroker=1.2.5
  - databroker-pack
  - hklpy>=1.0.1
  - ophyd>=1.6.3
  - pydm
  # --- user-requested packages
  - nexpy
  - punx
  - pvview
  - pymca
  - pyRestTable
  - spec2nexus
  - stdlogpj
  - xrayutilities
  - streamz
  - pip:
    # - apsbss
    - polartools
    # - https://github.com/BCDA-APS/adl2pydm/archive/main.zip
    # --- optional Bluesky framework packages for evaluation
    # - bluesky-queueserver-api
